### ISSUE TITLE
SDL_stbimage: undefined reference to `SDL_RWread'

### ISSUE THREAD

**Issue by nicholascc** [DanielGibson/Snippets#2]
I've added SDL_stbimage to my C++ project by placing both the SDL_stbimage.h header file and the stb_image.h header file in a folder called sdl_stbimage and including them as follows:

```
#define SDL_STBIMAGE_IMPLEMENTATION
#include "sdl_stbimage/SDL_stbimage.h"
```

I've also replaced SDL.h with SDL2/SDL.h in SDL_stbimage.h because otherwise I get a:

` fatal error: SDL.h: No such file or directory `

 When I compile my code with `g++ src/main.cpp -lSDL2main -lSDL2`, I get the following error:

```
/usr/bin/ld: /tmp/ccFlBkN9.o: in function `STBIMG__io_read(void*, char*, int)':
main.cpp:(.text+0x19ec0): undefined reference to `SDL_RWread'
/usr/bin/ld: /tmp/ccFlBkN9.o: in function `STBIMG__io_skip(void*, int)':
main.cpp:(.text+0x19f0d): undefined reference to `SDL_RWseek'
/usr/bin/ld: /tmp/ccFlBkN9.o: in function `STBIMG_Load_RW':
main.cpp:(.text+0x1a06f): undefined reference to `SDL_RWtell'
/usr/bin/ld: main.cpp:(.text+0x1a139): undefined reference to `SDL_RWseek'
/usr/bin/ld: main.cpp:(.text+0x1a22f): undefined reference to `SDL_RWclose'
/usr/bin/ld: main.cpp:(.text+0x1a252): undefined reference to `SDL_RWseek'
/usr/bin/ld: /tmp/ccFlBkN9.o: in function `STBIMG_Load_RW_noSeek':
main.cpp:(.text+0x1a2c1): undefined reference to `SDL_RWsize'
/usr/bin/ld: main.cpp:(.text+0x1a34d): undefined reference to `SDL_RWread'
/usr/bin/ld: main.cpp:(.text+0x1a387): undefined reference to `SDL_RWclose'
collect2: error: ld returned 1 exit status
```

How can I fix this? Thanks for the help, and I'm sorry if I'm missing something obvious; I'm new to programming in C++ so this is a bit confusing.

**Comment by DanielGibson** [comment]
What Linux distro are you using? What version of SDL2 is installed?
`SDL_RWread()` etc used to be macros in  older versions of SDL2, but now (since 2.0.10) they're proper functions.
So if for some reason it's using a newer SDL.h (that declares them to be functions) but an older libSDL2.so (that doesn't contain the function yet) that could explain the error you're getting.

**Comment by nicholascc** [comment]
Thanks for the info, especially at the end, it helped me solve the problem. Sorry to bother you, and I’ll close the issue.

**Comment by DanielGibson** [comment]
Great, glad it works now! :)
